# Generated by Django 3.2.7 on 2021-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='custom_ads')),
                ('ads_position', models.CharField(blank=True, choices=[('onload', 'While Loading'), ('on_header', 'Top Of The Site'), ('on_middle', 'Middle Of The Site')], max_length=255, null=True)),
            ],
        ),
    ]
