# Generated by Django 3.2.7 on 2021-10-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_socailmedialinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocailMediaLinks',
        ),
    ]
