# Generated by Django 3.2.7 on 2021-09-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(blank=True, default='', max_length=255, null=True)),
                ('status_code', models.IntegerField(blank=True, default=0, null=True)),
                ('added_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('added_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEditorNameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('added_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminPanel.newscategory')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPublisherList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('added_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos')),
                ('added_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_subcat', models.CharField(default='', max_length=255)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('news_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.newscategory')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPanel.newsgallery')),
            ],
        ),
        migrations.AddField(
            model_name='newsgallery',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminPanel.newssubcategory'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_types', models.CharField(blank=True, choices=[('general_news', 'General News'), ('lead_news', 'Lead News')], default='', max_length=255, null=True)),
                ('lead_types', models.CharField(blank=True, choices=[('lead_main', 'Main Lead News'), ('lead_minor_1', 'Small Top Lead News'), ('lead_minor_2', 'Small Bottom Lead News')], default='', max_length=255, null=True)),
                ('news_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('news_title', models.TextField(default='', max_length=255)),
                ('news_img', models.ImageField(upload_to='news_images')),
                ('news_img_short_description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('news_details', models.TextField(default='')),
                ('news_writer', models.CharField(blank=True, max_length=255, null=True)),
                ('news_writer_id', models.IntegerField(blank=True, default=0, null=True)),
                ('news_publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('news_publisher_id', models.IntegerField(blank=True, default=0, null=True)),
                ('news_tags', models.TextField(blank=True, default='', null=True)),
                ('number_of_visitor', models.IntegerField(blank=True, default=0, null=True)),
                ('division_of_news', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('zilla_of_news', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('upozilla_of_news', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('published_at', models.DateField(auto_now_add=True)),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminPanel.newscategory')),
                ('news_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminPanel.newssubcategory')),
            ],
        ),
    ]
