# Generated by Django 3.2.7 on 2021-09-22 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_alter_news_division_of_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminPanel.newssubcategory'),
        ),
    ]
