# Generated by Django 3.2.7 on 2021-09-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_alter_news_news_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_status',
            field=models.CharField(blank=True, choices=[('publish', 'Publish'), ('draft', 'Draft')], default='', max_length=255, null=True),
        ),
    ]
