# Generated by Django 3.2.7 on 2021-11-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0010_auto_20211110_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='banner_slider')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryBelowWithdrawBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='howToPlay')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='howToPlay')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='header_banner')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderRightIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='header_right_icon')),
            ],
        ),
        migrations.CreateModel(
            name='HowToPlayBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='howToPlay')),
            ],
        ),
        migrations.CreateModel(
            name='MinMaxWithdrawBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='howToPlay')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='payment_method_banner')),
            ],
        ),
        migrations.CreateModel(
            name='Welcome_bnner_Slider1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='welcome_bnr_slider1')),
            ],
        ),
        migrations.CreateModel(
            name='Welcome_bnner_Slider2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='welcome_bnr_slider1')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='welcome_banner')),
            ],
        ),
    ]
