# Generated by Django 3.2.7 on 2021-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0011_bannerslider_gallerybelowwithdrawbanner_gallerygames_headerbanner_headerrighticon_howtoplaybanner_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslider',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallerybelowwithdrawbanner',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gallerygames',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='headerbanner',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='headerrighticon',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='howtoplaybanner',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='minmaxwithdrawbanner',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethodsbanner',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='welcome_bnner_slider1',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='welcome_bnner_slider2',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='welcomebanner',
            name='link',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
